### ISSUE TITLE
Time mixing

### ISSUE THREAD

**Issue by faresobeid** [Artur-Galstyan/kira#1]
This is not an issue but more of a recommendation as I think ur project and journey is inspiring. For my own experiments, using the RWKV time mixing has worked very well for me (x = x*time_mix + sx*(1-time_mix)) where sx would be x but shifted one position back. If you want any help or any questions I'll be happy to work with you.

**Comment by Artur-Galstyan** [comment]
Hi there, thanks a lot for the kind words :)

I'm not familiar yet with RWKV, but found these interesting blog posts explaining the matter

https://johanwind.github.io/2023/03/23/rwkv_overview.html
https://johanwind.github.io/2023/03/23/rwkv_details.html

I'll take a deep dive into these topics to see if I can implement those and if these lead to an improvement in performance and/or efficiency.

**Comment by faresobeid** [comment]
Ya i mean most ideas will probably not be applicable however the time shifting and small initialization of the embeddings would be what i would try first. Lmk how it goes
